/**
 * Design tokens lifted verbatim from the Stitch export
 * (stitch_musclegrid_mobile_crm) so every ported screen's classes
 * — bg-surface-card, text-on-surface-variant, font-display-kpi, etc. —
 * resolve identically to the mockups.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#2c303d',
        'secondary-fixed': '#ffdbca',
        'text-secondary': '#94A3B8',
        'inverse-surface': '#dfe2f3',
        'on-primary-fixed-variant': '#003ea8',
        'on-background': '#dfe2f3',
        'tertiary-container': '#7d4ce7',
        'surface-container-highest': '#313442',
        background: '#0f131f',
        'error-container': '#93000a',
        'on-tertiary-container': '#f6edff',
        'on-tertiary-fixed-variant': '#5516be',
        'on-secondary-container': '#4a1c00',
        'tertiary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#00174b',
        'surface-dim': '#0f131f',
        'primary-container': '#2563eb',
        'border-subtle': '#1E293B',
        'primary-fixed': '#dbe1ff',
        'surface-variant': '#313442',
        warning: '#F59E0B',
        info: '#06B6D4',
        'on-error-container': '#ffdad6',
        surface: '#0f131f',
        'primary-fixed-dim': '#b4c5ff',
        'on-surface-variant': '#c3c6d7',
        tertiary: '#d0bcff',
        error: '#DC2626',
        'on-secondary-fixed-variant': '#783200',
        secondary: '#ffb690',
        primary: '#b4c5ff',
        'surface-container-high': '#262a37',
        'on-secondary': '#552100',
        'outline-variant': '#434655',
        'surface-overlay': '#000000',
        'on-error': '#690005',
        'surface-tint': '#b4c5ff',
        'surface-container-lowest': '#0a0e1a',
        'secondary-fixed-dim': '#ffb690',
        success: '#16A34A',
        'text-primary': '#F8FAFC',
        'surface-bright': '#353946',
        'surface-container-low': '#171b28',
        'on-primary-container': '#eeefff',
        'on-secondary-fixed': '#341100',
        'border-heavy': '#334155',
        'tertiary-fixed': '#e9ddff',
        outline: '#8d90a0',
        'on-primary': '#002a78',
        'surface-card': '#101726',
        'surface-container': '#1b1f2c',
        'on-tertiary': '#3c0091',
        'on-surface': '#dfe2f3',
        'secondary-container': '#ec6a06',
        'inverse-primary': '#0053db',
        'on-tertiary-fixed': '#23005c',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '24px',
        'margin-tablet': '24px',
        gutter: '16px',
        'touch-target': '48px',
        'stack-md': '16px',
        unit: '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-card': ['Inter'],
        'mono-data': ['JetBrains Mono'],
        'label-caps': ['Inter'],
        'display-kpi': ['Barlow Condensed'],
        'body-base': ['Inter'],
        'headline-nav': ['Inter'],
        'mono-data-sm': ['JetBrains Mono'],
        'body-bold': ['Inter'],
      },
      fontSize: {
        'headline-card': ['17px', { lineHeight: '22px', fontWeight: '600' }],
        'mono-data': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-kpi': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-nav': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'mono-data-sm': ['10px', { lineHeight: '12px', fontWeight: '500' }],
        'body-bold': ['15px', { lineHeight: '22px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
